Repository meta-convention-mtvs/chat-server, pull requests merged in 2024-11, with the labels that each got.

#19 Chore/modify recommandation base content
  .gitignore
  recommendation/data/3.unique_merged_data.json
  recommendation/data/4.company_keyword.json
  recommendation/data/5.unique_merged_data_with_key.json
  recommendation/data/company.index
  recommendation/data/company_metadata.json
  recommendation/service/recommendation.py
Labels: enhancement

#21 Feat/translate dummy server
  chat-server/EventHandler.py
  chat-server/MeetingRoom.py
  chat-server/RealtimeClient.py
  chat-server/main.py
  chat-server/translation_test.html
Labels: enhancement

#22 Feat/translation
  chat-server/MeetingRoom.py
  chat-server/RealtimeClient.py
  chat-server/iso_639_lang.py
  chat-server/prompt/translation.py
  chat-server/translation_test.html
Labels: enhancement

#25 feat: logging user-id and lang-code
  chat-server/RealtimeAPI.py
  chat-server/chatting_command.py
  chat-server/prompt/footer.py
Labels: enhancement

#30 Fix/add mudule six
  .env_sample
  docker-compose.yml
  summary/poetry.lock
  summary/pyproject.toml
Labels: bug

#31 Fix/nginx config
  .env_sample
  docker-compose.yml
  nginx.conf
Labels: bug, refactor

#38 Feat/modify indexing method
  recommendation/model/chatbot.py
  recommendation/service/recommendation.py
  recommendation/utils/data_management.py
Labels: refactor

#42 Refactor/add method for setting system prompt
  recommendation/config/chatbot_config.json
  recommendation/model/chatbot.py
  summary/model/chatbot.py
Labels: refactor

#54 Feat/add company data
  docker-compose.yml
  recommendation/config/chatbot_config.json
  recommendation/config/company_data_form.json
  recommendation/main.py
  recommendation/model/chatbot.py
  recommendation/model/firebase_client.py
  recommendation/poetry.lock
  recommendation/pyproject.toml
  recommendation/service/company_data_handle.py
  recommendation/utils/data_management.py
  recommendation/utils/file_util.py
  summary/model/chatbot.py
  summary/service/summary.py
  summary/utils/file_util.py
Labels: enhancement

#55 Refactor/make module for lifecycle
  recommendation/config/company_data_sample.json
  recommendation/lifecycle/firebase_event_listener.py
  recommendation/main.py
  recommendation/service/company_data_handle.py
Labels: refactor

#58 feat: add company uuid to company metadata
  recommendation/model/firebase_client.py
  recommendation/service/company_data_handle.py
Labels: enhancement
